# Form implementation generated from reading ui file 'c:\Users\Atlas\Python\PicoPayloadSender\ui\PayloadSenderUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PayloadSender(object):
    def setupUi(self, PayloadSender):
        PayloadSender.setObjectName("PayloadSender")
        PayloadSender.resize(751, 363)
        PayloadSender.setMinimumSize(QtCore.QSize(751, 363))
        PayloadSender.setMaximumSize(QtCore.QSize(751, 363))
        self.centralwidget = QtWidgets.QWidget(parent=PayloadSender)
        self.centralwidget.setMinimumSize(QtCore.QSize(751, 363))
        self.centralwidget.setMaximumSize(QtCore.QSize(751, 363))
        self.centralwidget.setObjectName("centralwidget")
        self.addressToConnectLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.addressToConnectLabel.setGeometry(QtCore.QRect(10, 15, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addressToConnectLabel.setFont(font)
        self.addressToConnectLabel.setObjectName("addressToConnectLabel")
        self.connectionAddressLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.connectionAddressLineEdit.setGeometry(QtCore.QRect(130, 20, 501, 22))
        self.connectionAddressLineEdit.setText("")
        self.connectionAddressLineEdit.setObjectName("connectionAddressLineEdit")
        self.connectionButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectionButton.setGeometry(QtCore.QRect(640, 20, 101, 24))
        self.connectionButton.setObjectName("connectionButton")
        self.payloadTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.payloadTextEdit.setGeometry(QtCore.QRect(0, 70, 551, 291))
        self.payloadTextEdit.setObjectName("payloadTextEdit")
        self.payloadLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.payloadLabel.setGeometry(QtCore.QRect(0, 50, 51, 21))
        self.payloadLabel.setObjectName("payloadLabel")
        self.payloadStatusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.payloadStatusLabel.setGeometry(QtCore.QRect(560, 320, 141, 21))
        self.payloadStatusLabel.setObjectName("payloadStatusLabel")
        self.connectionStatusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.connectionStatusLabel.setGeometry(QtCore.QRect(560, 280, 181, 16))
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.sendPayloadButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sendPayloadButton.setGeometry(QtCore.QRect(560, 90, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendPayloadButton.setFont(font)
        self.sendPayloadButton.setObjectName("sendPayloadButton")
        self.stopPicoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopPicoButton.setGeometry(QtCore.QRect(560, 190, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopPicoButton.setFont(font)
        self.stopPicoButton.setObjectName("stopPicoButton")
        PayloadSender.setCentralWidget(self.centralwidget)

        self.retranslateUi(PayloadSender)
        QtCore.QMetaObject.connectSlotsByName(PayloadSender)

    def retranslateUi(self, PayloadSender):
        _translate = QtCore.QCoreApplication.translate
        PayloadSender.setWindowTitle(_translate("PayloadSender", "Pico payload sender"))
        self.addressToConnectLabel.setText(_translate("PayloadSender", "Address to connect:"))
        self.connectionAddressLineEdit.setPlaceholderText(_translate("PayloadSender", "IP:Port"))
        self.connectionButton.setText(_translate("PayloadSender", "Connect"))
        self.payloadTextEdit.setPlaceholderText(_translate("PayloadSender", "Enter duckyscript payload to send."))
        self.payloadLabel.setText(_translate("PayloadSender", "Payload:"))
        self.payloadStatusLabel.setText(_translate("PayloadSender", "Payload status: None"))
        self.connectionStatusLabel.setText(_translate("PayloadSender", "Connection status: Disconnected"))
        self.sendPayloadButton.setText(_translate("PayloadSender", "Send payload"))
        self.stopPicoButton.setText(_translate("PayloadSender", "Stop Pico"))
